### PR TITLE
fix: Do not crash on bad pg_settings value

### LINKED ISSUE #1240: Crash when scraping managed Google Cloud SQL Postgres instance due to `google_dataplex.max_messages` setting
**What did you do?**

Our Cloud SQL Postgres instance updated overnight, and it now has a new setting in the `pg_settings` table.

**What did you expect to see?**

No impact.

**What did you see instead? Under which circumstances?**

The exporter now crashes with the following panic message.

```
panic: Error converting setting "google_dataplex.max_messages" value "-1:100" to float: strconv.ParseFloat: parsing "-1:100": invalid syntax

goroutine 57 [running]:
main.(*pgSetting).metric(0xc0003802d0, 0xc0000c4300)
	/app/cmd/postgres_exporter/pg_setting.go:86 +0x346
main.querySettings(0xc000085810, 0xc0000e4000)
	/app/cmd/postgres_exporter/pg_setting.go:55 +0x1d8
main.(*Server).Scrape(0xc0000e4000, 0xc000085810, 0x0?)
	/app/cmd/postgres_exporter/server.go:120 +0xc5
main.(*Exporter).scrapeDSN(0xc00015a180, 0xc000085810, {0xc000100700, 0x6a})
	/app/cmd/postgres_exporter/datasource.go:115 +0x12d
main.(*Exporter).scrape(0xc00015a180, 0xc000085810)
	/app/cmd/postgres_exporter/postgres_exporter.go:681 +0x16b
main.(*Exporter).Collect(0xc00015a180, 0xc000085810)
	/app/cmd/postgres_exporter/postgres_exporter.go:570 +0x25
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.23.1/prometheus/registry.go:458 +0xe5
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather in goroutine 53
	/go/pkg/mod/github.com/prometheus/client_golang@v1.23.1/prometheus/registry.go:548 +0xbf1
```

**Environment**

* System information:

We are using the Docker container image.

* postgres_exporter version:

`quay.io/prometheuscommunity/postgres-exporter:v0.18.1`

* postgres_exporter flags:

```
--web.listen-address=:9187
--log.format=json
```

* PostgreSQL version:

15.15

* Logs:
```
{"time":"2026-01-16T16:32:52.926069037Z","level":"WARN","source":"main.go:85","msg":"Error loading config","err":"error opening config file \"postgres_exporter.yml\": open postgres_exporter.yml: no such file or directory"}
{"time":"2026-01-16T16:32:52.926220207Z","level":"INFO","source":"main.go:95","msg":"Excluded databases","databases":"[]"}
{"time":"2026-01-16T16:32:52.928070872Z","level":"INFO","source":"tls_config.go:346","msg":"Listening on","address":"[::]:9187"}
{"time":"2026-01-16T16:32:52.928145615Z","level":"INFO","source":"tls_config.go:349","msg":"TLS is disabled.","http2":false,"address":"[::]:9187"}
{"time":"2026-01-16T16:33:37.336956402Z","level":"INFO","source":"server.go:73","msg":"Established new database connection","fingerprint":"127.0.0.1:5432"}
{"time":"2026-01-16T16:33:37.622250713Z","level":"INFO","source":"postgres_exporter.go:615","msg":"Semantic version changed","server":{},"from":"0.0.0","to":"15.15.0"}
panic: Error converting setting "google_dataplex.max_messages" value "-1:100" to float: strconv.ParseFloat: parsing "-1:100": invalid syntax

goroutine 57 [running]:
main.(*pgSetting).metric(0xc0003802d0, 0xc0000c4300)
	/app/cmd/postgres_exporter/pg_setting.go:86 +0x346
main.querySettings(0xc000085810, 0xc0000e4000)
	/app/cmd/postgres_exporter/pg_setting.go:55 +0x1d8
main.(*Server).Scrape(0xc0000e4000, 0xc000085810, 0x0?)
	/app/cmd/postgres_exporter/server.go:120 +0xc5
main.(*Exporter).scrapeDSN(0xc00015a180, 0xc000085810, {0xc000100700, 0x6a})
	/app/cmd/postgres_exporter/datasource.go:115 +0x12d
main.(*Exporter).scrape(0xc00015a180, 0xc000085810)
	/app/cmd/postgres_exporter/postgres_exporter.go:681 +0x16b
main.(*Exporter).Collect(0xc00015a180, 0xc000085810)
	/app/cmd/postgres_exporter/postgres_exporter.go:570 +0x25
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.23.1/prometheus/registry.go:458 +0xe5
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather in goroutine 53
	/go/pkg/mod/github.com/prometheus/client_golang@v1.23.1/prometheus/registry.go:548 +0xbf1

```

**Other information**

The new pg_settings row has the following values.

```
             name             | setting | unit |      category      |                    short_desc                    | extra_desc |  context   | vartype | source  | min_val | max_val | enumvals | boot_val | reset_val | sourcefile | sourceline | pending_restart 
------------------------------+---------+------+--------------------+--------------------------------------------------+------------+------------+---------+---------+---------+---------+----------+----------+-----------+------------+------------+-----------------
 google_dataplex.max_messages | -1:100  |      | Customized Options | Maximum number of pending notification messages. |            | postmaster | integer | default | -1      | 65536   |          | -1       | -1        |            |            | f
```

I noticed there is already an exception in the relevant query for an Azure database setting with `vartype = 'bool'` that has unexpected settings values. See #523 and #587. We could either fix this by adding another exception, or return a NaN in this situation. The existing code errs on the side of failing on unexpected values, in order to avoid missing metrics.

### PR DESCRIPTION
**Pull request by sysadmind**
pg_settings metrics would panic when the parsing fails. This is a poor experience for users. An exporter should not panic. This skips unparsable metrics and instead logs a warning.

fixes #1240

These tests are weird, but I think that's a future PR as we refactor.

### CODE REVIEW

File: exporter/pg_setting.go [hunk 1]
```diff
@@ -92,11 +97,11 @@ func (s *pgSetting) metric(labels prometheus.Labels) prometheus.Metric {
 		}
 	default:
 		// Panic because we got a type we didn't ask for
-		panic(fmt.Sprintf("Unsupported vartype %q", s.vartype))
+		return nil, fmt.Errorf("pgsetting: unsupported vartype %q", s.vartype)
```
Comment (cristiangreco) [inline exporter/pg_setting.go]: The comment above is outdated now with this change

**Review by cristiangreco — APPROVED** [review]
Left just a nitpick comment.

**Review by SuperQ — CHANGES_REQUESTED** [review]
Looks good, minor cleanup needed.

**Review by SuperQ — APPROVED** [review]

**Comment by evgenipetrov9** [comment]
When is the next release due with this fix included?

**Comment by gaeldb** [comment]
Thank you all for this+++

**Comment by cristiangreco** [comment]
> When is the next release due with this fix included?

Planning to cut a release this week
